[package]
name = "LabHelper"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.21.2"
hmac = "0.12.1"
if-addrs = "0.10.1"
lazy_static = "1.4.0"
md-5 = "0.10.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.99"
sha1_smol = "1.0.0"
ureq = "2.7.1"


